### ISSUE TITLE
Undefined index: hop

### ISSUE THREAD

**Issue by oleteacher** [bigbeastmarketing/ClickBankURLRotator#2]
Hey! Nice little compact script.

Everything setup, but running get this error:

`Notice: Undefined index: hop in /opt/lampp/htdocs/testbed/clickbank/index.php on line 37`

Any tips to get it working?

The ads are not showing at all. Have manually downloaded the marketplace feed for now just to test, so it is present. All Isee is this:

![image](https://user-images.githubusercontent.com/26278259/99157560-9102f100-268f-11eb-9aae-ed407309e873.png)

**Comment by bigbeastmarketing** [comment]
Did you put your nickname in config.php? You can also use $_GET["hop"] as a url parameter... Such as ?hop=yourNick

**Comment by bigbeastmarketing** [comment]
what os is that? look at the fetch.php script, and put a wget, and an unzip... I can look it up... is that a bsd operating system?

**Comment by bigbeastmarketing** [comment]
I figured out what it was... You need mod_php installed in you're configuration... I installed it on a new server, and it did the same thing.  I installed mod_php and it works!

**Comment by oleteacher** [comment]
Sorry, I totally missed your earlier replies.

Thank you for taking time to figure it out!

**Comment by bigbeastmarketing** [comment]
Try it again... Pull it... I worked on it again... I put debian 10 on my VPS... It should work... I used native PHP code (there's no modules or anything)
